version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: oews_onet
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: